[FEATURE] Add linkToDocs.php helper script
TYPO3GmbH/site-intercept pull request #188
Opened 2024-09-24 13:34 UTC by garvinhicking

Allows to call an "API endpoint" on docs.typo3.org which can redirect to a common intersphinx identifier (like "t3coreapi:caching").

Version dependencies can also be specified.

This is possible by looking up a objects.inv.json
file inside the resolved directory of the
docs.typo3.org server, parse it, search for the
index and then forward to the target URI.

We do not need an aggregator to merge all possible JSON files into one, because we only need to lookup the specific intersphinx repository destination.

Composer dependency 't3docs/typo3-version-handling' is utilized to provide the needed lookup maps
between "intersphinx identifier" and actual
rendering directory.

Example calls:

https://intercept.ddev.site/services/linkToDocs.php?shortcode=t3renderguides:available-default-inventories

https://intercept.ddev.site/services/linkToDocs.php?shortcode=t3coreapi:caching@12.4

https://intercept.ddev.site/services/linkToDocs.php?shortcode=t3coreapi:caching@11.5

https://intercept.ddev.site/services/linkToDocs.php?shortcode=t3coreapi:caching@main

https://intercept.ddev.site/services/linkToDocs.php?shortcode=typo3-cms-seo:introduction@main

2024-09-24 13:34 UTC, garvinhicking commented
c/o @NeoBlack - as discussed

2024-09-26 08:10 UTC, andreaskienast requested changes

2024-09-26 08:10 UTC, andreaskienast commented on legacy_hook/src/DocumentationLinker.php
> +            if (!is_array($json)) {
You may use `json_validate($objectsContents)` to check whether it's a valid JSON string.

2024-09-26 08:10 UTC, andreaskienast commented on legacy_hook/src/DocumentationLinker.php
> +        return preg_replace('/^.*:\/\/[^\/]+\//imsU', '', $entrypoint);
My IDE reports:
> [EA] 'i' modifier is ambiguous here (no alphabet characters in given pattern).

2024-09-26 08:10 UTC, andreaskienast commented on legacy_hook/src/DocumentationLinker.php
> +            $entrypoint = $this->resolveEntryPoint($repository, $version);
In general: I think having a cache for entry point resolving and object file parsing has a great benefit.

2024-09-26 08:19 UTC, garvinhicking commented on legacy_hook/src/DocumentationLinker.php
> +            $entrypoint = $this->resolveEntryPoint($repository, $version);
I agree. I did not know what the infrastructure offers for this. A local database? SQLite? Redis? File-based?

2024-09-26 08:21 UTC, garvinhicking commented on legacy_hook/src/DocumentationLinker.php
> +        return preg_replace('/^.*:\/\/[^\/]+\//imsU', '', $entrypoint);
Nice IDE feature, need to check on that. I just use 'imsU' by muscle memory. Will change.

2024-09-26 08:24 UTC, garvinhicking commented on legacy_hook/src/DocumentationLinker.php
> +            if (!is_array($json)) {
done

2024-09-26 08:24 UTC, andreaskienast commented on legacy_hook/src/DocumentationLinker.php
> +            $entrypoint = $this->resolveEntryPoint($repository, $version);
The server is pretty "dumb", it has plain PHP, nothing else. I suggest to use `symfony/cache` and write file-based caches. If you're unsure how to implement this, I can take a look by myself.

2024-09-26 08:27 UTC, andreaskienast commented on legacy_hook/src/DocumentationLinker.php
> +            if (!is_array($json)) {
Technically, the `if (!is_array($json)) {` branch is not needed anymore ;)

2024-09-26 08:39 UTC, garvinhicking commented on legacy_hook/src/DocumentationLinker.php
> +            $entrypoint = $this->resolveEntryPoint($repository, $version);
I haven't used that one yet. I could happily investigate and check, but it might take me a few days or maybe weeks to address this and set aside some time. If you're skilled with using it, of course I would appreciate your help. :-)

2024-09-26 08:39 UTC, garvinhicking commented on legacy_hook/src/DocumentationLinker.php
> +            if (!is_array($json)) {
I thought maybe an objects.inv.json file might contain "NULL" (string). That would be valid JSON, but not a valid array. Better safe than sorry? ;-)

2024-09-26 08:44 UTC, andreaskienast commented on legacy_hook/src/DocumentationLinker.php
> +            if (!is_array($json)) {
Argh. I'm sorry, `json_validate()` is available in PHP 8.3 only, but the server still runs PHP 8.2.

Anyway, it'd be better to check `$objectsContents` for being null before handing it to `json_validate()` or `json_encode()`, as it will trigger a deprecation in PHP 8.4.

2024-09-26 08:50 UTC, garvinhicking commented on legacy_hook/src/DocumentationLinker.php
> +            if (!is_array($json)) {
I've changed this to check for json_validate now. I looked it up, valid json would also be a string or integer value, so IMO keeping the is_array check would be beneficial, before we add specific checks for NULL and is_string(), ok?

2024-09-26 08:51 UTC, andreaskienast commented on legacy_hook/src/DocumentationLinker.php
> +            if (!is_array($json)) {
Ack

2024-09-30 07:42 UTC, garvinhicking commented on legacy_hook/src/DocumentationLinker.php
> +            $entrypoint = $this->resolveEntryPoint($repository, $version);
Had to check it out, was easier than I thought, please see if it is usable like this

2024-10-02 10:35 UTC, andreaskienast commented on legacy_hook/composer.json
> +        "symfony/cache": "^7.1"
Can you please use `^5.4` (to be in line with `symfony/finder`)? While at it, do you mind executing `composer config sort-packages true` once?

2024-10-02 14:10 UTC, garvinhicking commented on legacy_hook/composer.json
> +        "symfony/cache": "^7.1"
Done (by you ;)

2024-10-02 14:10 UTC, garvinhicking commented on legacy_hook/src/DocumentationLinker.php
> +            $entrypoint = $this->resolveEntryPoint($repository, $version);
Resolving this. Your refactoring of this looks very useful to me, thanks.

2024-10-02 14:28 UTC, andreaskienast approved these changes

2024-10-02 14:28 UTC, merged