[BUGFIX] Trigger docs rendering for standalone files
TYPO3GmbH/site-intercept pull request #24
Opened 2020-11-08 10:57 UTC by sypets

Make sure that rendering documentation is triggered for standalone
README files as well.

Currently, supplying documentation in a dedicated Documentation
directory is supported, but also using standalone README.md or
README.rst files without the Documentation directory.

For extensions, this has the advantage that the documentation
is visible immediatedly when visiting the project on the
git hoster (e.g. GitHub) and may be a better fit for extensions
with only minimal documentation.

In any case, it is recommended to add Documentation/Settings.cfg,
so that the title is generated correctly.

Related: TYPO3-Documentation/T3DocTeam#152

2020-11-09 07:04 UTC, andreasfernandez requested changes

2020-11-09 07:04 UTC, andreasfernandez commented on src/Service/WebHookService.php
> +                        || strpos($file, 'README.md') === 0
why not `$file === 'README.md'`?

2021-04-23 07:09 UTC, andreasfernandez commented on src/Service/WebHookService.php
> +                        || strpos($file, 'README.md') === 0
@sypets nearly half a year has gone without feedback. Is this change still required at all?

2021-04-23 10:29 UTC, sypets commented on src/Service/WebHookService.php
> +                        || strpos($file, 'README.md') === 0
You are right, a simple string compare could have been used. 

Will push a change. 

Sorry about long delay. Probably overlooked this in the many notifications I get. 

---

The rendering of a standalone README.rst works, (probably also with README.md). What did not work previously was that a rerendering of the docs was not triggered on changes. 

---

I am not really involved with docs that much anymore. I would talk with documentation team. 

What I noticed a lot is that extension authors do not generally always "embrace" the solution with rendering on docs. typo3.org. And often only have a standalone README. So I think improving this (and making Settings.cfg obsolete) might be helpful.

2021-04-23 10:54 UTC, andreasfernandez approved these changes

2021-04-23 10:58 UTC, merged