[TASK] Replace `git@github.com:` by `git://github.com/`
TYPO3GmbH/site-intercept pull request #48
Opened 2021-08-23 09:40 UTC by alexander-nitsche

See https://github.com/TYPO3-Documentation/T3DocTeam/issues/162 for details.

2021-08-23 11:47 UTC, andreasfernandez requested changes

2021-08-23 11:47 UTC, andreasfernandez commented on .env
> +CORE_SPLIT_MAIN_REPO_V8="git://github.com/TYPO3GmbH/elts-8.7-release.git"
Are you sure about this? If I try to clone with `git clone git://github.com/TYPO3GmbH/elts-8.7-release.git`, I get the following output:
```
Cloning into 'elts-8.7-release'...
fatal: remote error: 
  Repository not found.
```

2021-08-23 11:48 UTC, andreasfernandez commented on .env
> +CORE_SPLIT_MAIN_REPO_V8="git://github.com/TYPO3GmbH/elts-8.7-release.git"
Interestingly, this works with public repositories. It seems with `git://` there's no access check.

2021-08-24 07:33 UTC, alexander-nitsche commented on .env
> +CORE_SPLIT_MAIN_REPO_V8="git://github.com/TYPO3GmbH/elts-8.7-release.git"
Thanks for testing this.

2021-08-24 07:33 UTC, alexander-nitsche commented
Stop. `git@github.com:` should be kept and `git://github.com/` be dropped instead. See https://github.com/TYPO3-Documentation/T3DocTeam/issues/163 for further details. Closing this PR.

2021-08-24 07:34 UTC, closed without merging