[FEATURE] Add documentation validator
TYPO3GmbH/site-intercept pull request #73
Opened 2022-05-06 22:41 UTC by alexander-nitsche

The documentation validator checks the documentation's reST files and Settings.cfg for compliance with the recently introduced TYPO3 documentation standards [1][2] and lists selected errors. The authors identified by composer.json are notified and the Intercept history log provides the validation errors for the remaining contributors.

For now, the validation errors are handled gently and documentation rendering is performed anyway. After a sufficient grace period, strict validation will be introduced.

[1] https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/GeneralConventions/FileStructure.html
[2] https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/UserRoundTrip.html

2022-05-06 22:47 UTC, alexander-nitsche commented
This is how the new email format looks like:
![Screen Shot 2022-05-07 at 00 46 36](https://user-images.githubusercontent.com/20297232/167225269-28d5395e-ac9d-456b-8887-25a903dcf597.png)

2022-05-06 22:50 UTC, alexander-nitsche commented
This is how the history log entry of a successful documentation rendering with a validation warnings looks like:
![Screen Shot 2022-05-07 at 00 49 15](https://user-images.githubusercontent.com/20297232/167225429-3cb0170c-ad34-4e7b-865e-841e6ffc0d04.png)

2022-05-07 07:54 UTC, alexander-nitsche commented
Slightly optimized the email to:
![Screen Shot 2022-05-07 at 09 53 30](https://user-images.githubusercontent.com/20297232/167244776-d369740c-d9e9-4837-974d-9663290d3493.png)

2022-07-11 12:38 UTC, NeoBlack commented on src/Service/MailService.php
> +                    ->setCc(array_map(function ($author) {
Why CC and not TO?

2022-07-11 13:43 UTC, alexander-nitsche commented on src/Controller/DocsRenderingController.php
> +                    // Handle documentation validation errors gently for a grace period. Remove this try-catch wrap
The idea of the grace period is to collect feedback and improve the validator in production. I assume that there will be some feedback as soon as authors are publishing new documentation versions, so i would tend to have a longer grace period, maybe half a year. The is no deadline i would commit to for now.

2022-07-11 13:46 UTC, alexander-nitsche commented on src/Service/MailService.php
> +                    ->setCc(array_map(function ($author) {
This is for historic reasons: The first author mentioned in the composer.json was the only recipient before this patch. now (s)he still is special by being to only one in TO, and the rest is in CC. This was only a stylistic reason, no fundamental one.

2022-07-11 13:47 UTC, alexander-nitsche commented on src/Service/MailService.php
> +                    ->setCc(array_map(function ($author) {
See above.

2022-07-11 13:54 UTC, alexander-nitsche commented on src/Extractor/ComposerJson.php
> +            return filter_var($author['email'] ?? '', FILTER_VALIDATE_EMAIL);
This filter was in use before this patch already. Furthermore it is used also in other places of this project already, see e.g.
```
vendor/phar-io/manifest/src/values/Email.php
vendor/phpdocumentor/reflection-docblock/src/DocBlock/Tags/Author.php
vendor/symfony/maker-bundle/src/Validator.php
vendor/webmozart/assert/src/Assert.php
```

I think this is not a critical part that must be 100% correct, as we are not sending critical data in the email, but if you would like to switch to a different validation, please tell me which. The \Egulias\EmailValidator\EmailValidator?

2022-07-11 15:10 UTC, linawolf requested changes
We do not have strict TYPO3 Documentation standards. We merely have guidelines that we do not intent to enforce. So I as Co-Team-Lead do not agree with enforcing these guidelines. Therefore this PR is not needed and contra-productive as it would just cause much work to many extension owners without any clear benefit.

2022-07-12 08:59 UTC, alexander-nitsche commented
We have standards and any check of documentation, that can be performed automatically, should be performed automatically. There is no benefit in sticking to manual checks or no checks at all. Automatic checks help being productive by allowing to concentrate on different topics.

2022-07-29 09:06 UTC, linawolf commented
So, I asked Martin about it and we both decided that this is neither needed nor wanted. @NeoBlack please close.

2022-07-29 09:08 UTC, NeoBlack commented
As decided by the documentation team leaders, I close this PR.

2022-07-29 09:08 UTC, closed without merging