[BUGFIX][COMMUN-434] JsonException: Syntax error
TYPO3GmbH/site-intercept pull request #93
Opened 2022-09-22 10:55 UTC by plovinda

2022-09-26 05:49 UTC, andreasfernandez requested changes

2022-09-26 05:49 UTC, andreasfernandez commented on src/Service/WebHookService.php
> +            if ($payload === null) {
`$payload === null` will never work if `JSON_THROW_ON_ERROR` is used. Anything within this condition belongs into `catch()`, with another nested try/catch .

2022-09-26 05:50 UTC, andreasfernandez commented on tests/Unit/Service/WebHookServiceTest.php
> +        //Creates a request with json containing syntax error
To make the test more readable, please explain what causes the JSON to be invalid.

2022-09-29 09:21 UTC, NeoBlack approved these changes

2022-09-29 09:24 UTC, andreasfernandez approved these changes

2022-09-29 09:24 UTC, merged