[BUGFIX][COMMUN-435] Add exception handling
TYPO3GmbH/site-intercept pull request #94
Opened 2022-09-23 06:57 UTC by plovinda

Add subscriber for exception handling of suspicious operation exception, add test.

2022-09-23 07:06 UTC, andreasfernandez reviewed
I don't understand how this fixes the issue reported in the ticket.

`Invalid method override "__CONSTRUCT"` looks to me like some internal code in intercept is broken.

2022-09-23 07:09 UTC, andreasfernandez commented
> I don't understand how this fixes the issue reported in the ticket.
> 
> `Invalid method override "__CONSTRUCT"` looks to me like some internal code in intercept is broken.

Alright, this happens if a request sent to intercept contains an invalid HTTP method (GET, POST, PATCH, etc).

2022-09-23 07:12 UTC, andreasfernandez requested changes

2022-09-23 07:12 UTC, andreasfernandez commented on tests/Functional/EventSubscriber/ExceptionSubscriberTest.php
> +        $this->assertInstanceOf(SuspiciousOperationException::class, $event->getThrowable());
You're testing something you pass into the method two lines above. You should rather test whether `$event->getResponse()` contains the expected data.

2022-09-26 13:05 UTC, plovinda commented on tests/Functional/EventSubscriber/ExceptionSubscriberTest.php
> +        $this->assertInstanceOf(SuspiciousOperationException::class, $event->getThrowable());
$event->getResponse returns null. I tried to mock kernal exception to see if ExceptionSubscriber is called. It did not work, so removed the test.

2022-09-29 09:09 UTC, andreasfernandez commented
We won't fix this issue. Symfony reacts correctly by sending a "Bad Request".

2022-09-29 09:09 UTC, closed without merging